version: '3.9'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

